azure:
    storage:
        connection:
            string: 'DefaultEndpointsProtocol=https;AccountName=acountName;AccountKey=accountKey;EndpointSuffix=core.windows.net'
        container:
            name: 'test'


server:
    port: 8083
